### PR TITLE
Initial version

### PR DESCRIPTION
**Pull request by jritsema**

### CODE REVIEW

**Comment by abarfoot** [comment]
Dashboard should be updated, because the HTTP-related stats are N/A.  Got an NLB up so we can poke around in CloudWatch to see what stats are available?

**Review by abarfoot — APPROVED** [review]

**Comment by jritsema** [comment]
Good catch.

**Review by awlawl — APPROVED** [review]

**Review by jhodnett2 — APPROVED** [review]
I approve!

**Comment by abarfoot** [comment]
Maybe just delete the dashboard?

**Pull request merged**
